### ISSUE TITLE
Unable to merge & update entries and results In creation of duplicated entries

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/csv2notion-neo#13]
Summary of user's findings - 

I just ran into a small issue with CSV2Notion Neo. Not sure what's happening, because it will create new entries from my `.csv` instead of updating the items.

I've already tried it without importing the Images and also the `--merge-only-column` instead of `--merge` switch.

**Comment by arjunprakash027** [comment]
@vzhd1701 Hi, I Noticed a problem with csv2notion tool,  the --merge sometimes dosent work.
I backtracked and found out some problems.

1) in notion_uploader.py file, in NotionRowUploader class -> _get_db_row method. exisiting row value becomes none sometimes even when is_merge flag is True.
2) Tracking that back, i found that in file notion_db.py -> NotionDB class -> rows method, self.collection.get_unique_rows() return none sometimes.
3) when tracing it again, i was directed to notion_db_collection.py file -> get_rows, where super.get_rows() function returns None, ie a []. I suppose Collection is an inherited class from notion-py package. 

Do you have any idea on why this happens? 
Thank you in advance

**Comment by IAmVigneswaran** [comment]
I believe based on @samplue feedback and report we have fixed this issue.
