### ISSUE TITLE
Add Repo URL in CLI

### ISSUE THREAD

**Issue by IAmVigneswaran** [TheAcharya/csv2notion-neo#5]
@arjunprakash027 As discussed, let's add our repo URL in between the "usage:" and CLI description.

```
usage: csv2notion_neo [-h] --token TOKEN [--url URL] [OPTION]... FILE

https://github.com/TheAcharya/csv2notion-neo

Upload & Merge CSV Data with Images to Notion Database
```

I have made an edit to this file.

https://github.com/TheAcharya/csv2notion-neo/blob/master/csv2notion_neo/cli_args.py

Please check if this is correct and working.

Thank you.

**Comment by arjunprakash027** [comment]
the changes you made in cli_args.py is sufficient.
